# Site settings
title: Colin Clement 
email: colin.clement@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Colin Clements's website."
baseurl: "" #"/cbclement"
url: "https://colinclement.github.io/cbclement" # the subpath of your site, e.g. /blog/
github_username:  colin.clement

# Build settings
sass:
  sass_dir: _sass
  style: compressed #minify css
include: ['_pages']
kramdown:
  input: GFM
lsi: true
future: true
