# Site Settings
title: Colin Clement 
email: colin.clement@gmail.com 
description: >
  A guide to getting started with Jekyll.
baseurl: ""
url: "http://colinclement.github.io/cbclement"
github_username:  colin.clement 
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
