# Site Settings
title: Colin Clement 
email: colin.clement@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website about Colin.
baseurl: ""
url: "http://localhost:4000" # the subpath of your site, e.g. /blog/
github_username:  colin.clement

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
